F#src 3166/improve controller new
shadow-robot/sr_core pull request #134
Opened 2019-07-01 15:58 UTC by azompas

## Proposed changes

Please explain the changes you made. Add pictures or videos to explain them better if appropiate.

## Types of changes

What types of changes does your code introduce?

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. This is a reminder of what we should look for before merging this code. I have:_ 

- [ ] Read and follow the [contributing guidelines](https://github.com/shadow-robot/sr_documentation/blob/master/CONTRIBUTING.md).
- [ ] Checked that all tests pass with my changes
- [ ] Added tests (automatic or manual) that prove the fix is effective or that the feature works
- [ ] Added necessary documentation (if appropriate)
- [ ] Added the corresponding license to each file and add the current year of any one that you modified.
- [ ] Tested on real hardware (if appropriate)

2019-07-02 09:19 UTC, mikramarc requested changes

2019-07-02 09:19 UTC, mikramarc commented on sr_mechanism_controllers/include/sr_mechanism_controllers/srh_joint_variable_pid_position_controller.hpp
> +  double position_deadband;
all class variables should end with a trailing underscore

2019-07-02 09:19 UTC, mikramarc commented on sr_utilities/scripts/sr_utilities/trajectory_controller_spawner.py
> +    variable_controller = rospy.get_param("~variable_controller", True)
have we decide we want this to be run as default?

2019-07-05 10:08 UTC, azompas commented on sr_mechanism_controllers/include/sr_mechanism_controllers/srh_joint_variable_pid_position_controller.hpp
> +  double position_deadband;
I didn't add this but probably I should modify it

2019-07-08 09:34 UTC, mikramarc approved these changes

2019-07-08 09:39 UTC, merged