F fixing trajectory publisher bug
shadow-robot/sr_core pull request #199
Opened 2021-10-22 13:15 UTC by mikramarc

## Proposed changes

Current implementation of trajectory publisher has two issues:
1. It doesn't support trajectories with more points than one. This is fine for things like arm servoing, however, if we ever use it for different purposes it might become an issue.
2. **It effectively discards the first trajectory that user wants to send**. Again, this is fine for things like arm servoing when we are continuously sending trajectories, but for use cases when one would like to send single trajectories under specific circumstances it would generate buggy behaviour.

This PR fixes both of those issues, the latter by setting up publishers at start-up instead of on demand. There are two ways to create the main object, either without any arguments - that way the object will initialize with all possible available trajectory publisher objects, or with joints vector passed to the constructor - this way the class will initialize only with publishers that correspond to the passed-in joints, i.e. won't start with unused publishers.

## Checklist

Before posting a PR ensure that from each of the below categories **AT LEAST ONE BOX HAS BEEN CHECKED**. If more than one category is applicable then more can be checked. Also ensure that the proposed changes have been filled out with relevant information for reviewers.

## Tests

- [ ] No tests required to be added. (For small changes that will be tested by CI/CD infrastructure).
- [ ] Added automated tests (if a new class is added (Python or C++), the interface of that class must be unit tested).
- [x] Manually tested in simulation (if simulation specific or no hardware required to test the functionality). 
- [ ] Manually tested on hardware (if hardware specific or related).

## Documentation

- [x] No documentation required to be added.
- [ ] Added documentation (For any new feature, explain what it does and how to use it. Write the documentation in a relevant space, e.g. Github, Confluence, etc).
- [ ] Updated documentation (For changes to pre-existing features mentioned in the documentation).

2021-10-25 09:11 UTC, toliver requested changes

2021-10-25 09:11 UTC, toliver commented on sr_utilities/src/sr_trajectory_command_publisher.cpp
> -  throw std::runtime_error("There is no trajectory controller specified in /move_group/controller_list for joint " +
This msg should appear somewhere, shouldn't it?
Whether it is in setup_publisher, or in publish() or both, but the user should get an error.

2021-10-25 11:37 UTC, toliver approved these changes

2021-10-27 07:36 UTC, georgiablanco approved these changes

2021-10-27 07:37 UTC, merged